distributionName: hello-world
initDeployConfig:
  template: deployment-plan.yaml # The path to the deployment plan template, find more info here: https://docs.attini.io/getting-started/create-your-first-deployment-plan.html
  stackName: ${environment}-${distributionName}-deployment-plan # The stack name for the init deployment, this stack will for example be called "dev-hello-world-deployment-plan"
  parameters: # Parameters for the init deployment stack, the first key represent the environment
    default: # The "default" key will be used if the environment that you are deploying to do not have the specific config
      ConfigEnvironment: dev # This is used as a pattern to re-use config for many environments, now we can deploy to ex "dev1" and "dev2" and they will use the same configuration
      ParameterValue: cruel world
    stage:
      ConfigEnvironment: prod # We want the staging environment to use the same configuration file as out production environment
      ParameterValue: staging world
    prod:
      ConfigEnvironment: prod
      ParameterValue: real world

package: # When you use the Attini CLI to "package" a distribution, these instructions will be used, find more info here https://docs.attini.io/api-reference/attini-configuration.html
  prePackage:
    commands: # These shell commands will be executed in a temporary copy of your files, so they will not affect your source files
      - echo "Setting the distribution id to random"
      - attini configure set-dist-id --id `date '+%Y-%m-%d_%H:%M:%S'`
        # Using the Attini CLI to set the distribution id to the current time.
        # We recommend you to use a meaningful and unique value, for example, a git commit id.
