AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  AttiniEnvironmentName:
    Type: String

  SsmParameterKey:
    Type: String

  MemorySize:
    Type: String

  Runtime:
    Type: String

  Timeout:
    Type: String

Resources:

  HelloWorldLambda:
    Type: AWS::Serverless::Function
    Properties:
      Description: Lambda that fetches the hello-world SSM Parameter
      FunctionName: !Sub ${AttiniEnvironmentName}-hello-world-get-parameter
      InlineCode: |
          import json
          import boto3
          import os
          ssm_client = boto3.client('ssm')

          def lambda_handler(event, context):

            parameter = ssm_client.get_parameter(
                Name=os.environ["SsmParameterKey"]
            )["Parameter"]["Value"]

            return {
                "statusCode": 200,
                "body": f"Hello {parameter}\n"
            }

      Environment:
        Variables:
          SsmParameterKey: !Ref SsmParameterKey
      Handler: index.lambda_handler
      MemorySize: !Ref MemorySize
      Runtime: !Ref Runtime
      Timeout: !Ref Timeout
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET
      Policies:
        Statement:
          - Effect: Allow
            Action:
            - ssm:GetParameter
            Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${SsmParameterKey}


  HelloWorldLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${HelloWorldLambda}
      RetentionInDays: 30


Outputs:
  Endpoint:
    Description: API Gateway URL
    Value: !GetAtt ServerlessHttpApi.ApiEndpoint