AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AttiniEnvironmentName:
    Type: String

  ParameterValue:
    Type: String

Resources:

  HelloWorldParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: This is a hello world parameter
      Name: !Sub /${AttiniEnvironmentName}/hello-world
      Type: String
      Value: !Ref ParameterValue

Outputs:

  SsmParameterKey: # Output the parameter key so that it can be read by subsequent steps in the deployment plan.
    Value: !Ref HelloWorldParameter